import type { Metadata } from "next";
import localFont from "next/font/local";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const solaimainLipi = localFont({
  src: "./fonts/SolaimanLipi.ttf",
  variable: "--font-sans",
});

const JetBrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-serif",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Enews71",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${solaimainLipi.variable} ${JetBrains.variable} antialiased`}
      >
        <Header />
        <main className="min-h-[calc(100vh-424px)]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
